### ISSUE TITLE
Cant find Weater station on Wordress plugin download page

### ISSUE THREAD

**Issue by Duhlin12** [Weather-Station-Software/live-weather-station#25]
Hi

I¨am not able to find weather station on wordpress download site?

**Comment by jaz-on** [comment]
Duplicate of #23.

@Duhlin12 FYI the plugin is temporarily unavailable on the WordPress.org official repository.
Nothing to worry about. A security fix is on the way to reactivate the plugin on the official repository.
Have a look at the linked issue for more details.

**Comment by jaz-on** [comment]
In the meantime, you can download the plugin from this repository:
https://github.com/Weather-Station-Software/live-weather-station/releases

I advise you to download version 3.8.12 for now (which is the latest approved version on WordPress repository).

FYI I've just deployed version 3.8.13 a few minutes ago, which has been sent for validation to the WordPress.org plugin review team to reactivate the plugin page on the website. Once approved, you'll be prompt to update the plugin on your website to this new version.

**Comment by jaz-on** [comment]
See update on #23: the plugin is back online.
