### ISSUE TITLE
Improved plugin description

### ISSUE THREAD

**Issue by szepeviktor** [Weather-Station-Software/live-weather-station#28]
> Display meteorological data collected by public or personal weather stations on your WordPress site in a variety of elegant ways. 

- repository details (**About** ⚙️)
- README.md
- readme.txt
- composer.json
- plugin header

Please consider using the above description. Or improve upon it.

**Comment by szepeviktor** [comment]
ChatGPT and DeepL Writer helped.

**Comment by jaz-on** [comment]
Hmm I don't see the point of changing the description. The actual desc used for years seems good enough to me:

> Weather Station is a plugin that allows you to display, on your WordPress site, meteorological data from weather stations you have access to. It provides full support for [many models of weather stations and for free or paid services](https://weather.station.software/handbook/technical-specifications/)&hellip;
> Whether you own a weather station or not, you can enjoy the power of Weather Station!

I'm closing this issue.

**Comment by szepeviktor** [comment]
Many thing on GitHub are name in imperative. (L’impératif 🇫🇷)

"Verb + object" like _Do this_
